App\Entity\Task:
    properties:
        owner:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
                minMessage: 'El propietario debe tener al menos {{ limit }} caracteres'
                maxMessage: 'El propietario no puede tener más de {{ limit }} caracteres'
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
                minMessage: 'El título debe tener al menos {{ limit }} caracteres'
                maxMessage: 'El título no puede tener más de {{ limit }} caracteres'
        isCompleted:
            - Type: bool
